/**
 * @file frontend/src/utils/metaTags.ts
 */

// A "upsert" helper: if a meta tag already exists, update its content;
// if not, create it. Every call site (usePageMeta below) can call this
// without ever needing to check "does this tag exist yet?" itself.
function upsertMetaTag(
  attribute: "name" | "property",
  key: string,
  content: string,
): void {
  // querySelector finds the FIRST existing tag matching e.g. [name="description"]
  let tag = document.querySelector<HTMLMetaElement>(
    `meta[${attribute}="${key}"]`,
  );

  if (!tag) {
    tag = document.createElement("meta");
    tag.setAttribute(attribute, key);
    document.head.appendChild(tag);
  }

  tag.setAttribute("content", content);
}

// "name" attributes (description, robots) vs "property" attributes
// (og:title, og:description) are two DIFFERENT real-world conventions —
// Open Graph tags (used by Facebook/Slack/Discord link previews) always
// use "property", standard SEO meta tags always use "name". Two small
// wrapper functions keep call sites from ever mixing these up by hand.
export function setMetaName(name: string, content: string): void {
  upsertMetaTag("name", name, content);
}

export function setMetaProperty(property: string, content: string): void {
  upsertMetaTag("property", property, content);
}

/**
 * Canonical links.
 * Word check — "canonical URL": the one "official" URL for a piece of content
 * used to tell crawlers "if you found this content at several different URLs,
 * treat this one as the real one."
 * Our product search page can be reached via /, /?q=phone, /?q=phone&page=2
 * — all showing overlapping content.
 * Without a canonical tag, search engines can split ranking signals
 * across all these near-duplicate URLs instead of consolidating them.
 */

// Same upsert idea, but for the single <link rel="canonical"> tag —
// there should only ever be ONE per page, so we don't need a "key" param.
export function setCanonicalLink(href: string): void {
  let link = document.querySelector<HTMLLinkElement>('link[rel="canonical"]');

  if (!link) {
    link = document.createElement("link");
    link.setAttribute("rel", "canonical");
    document.head.appendChild(link);
  }

  link.setAttribute("href", href);
}

/**
 * JSON-LD structured data on product pages.
 * Word check — "structured data" / "JSON-LD":
 * a small <script type="application/ld+json"> block
 * containing machine-readable facts about the page's content
 * (product name, price, availability) in a standard vocabulary (schema.org)
 * that Google explicitly documents support for.
 * This is what enables rich search results
 * — star ratings, price, "in stock" badges directly in search listings
 * — and it's one of the few SEO wins that works well even in a JS-rendered SPA
 * since Googlebot specifically looks for it after rendering.
 */

// Injects (or replaces) a single <script type="application/ld+json">
// block, identified by a unique "id" so multiple structured-data blocks
// could coexist without colliding (we only use one at a time today, but
// this keeps the function correct if that ever changes).
export function setJsonLd(id: string, data: Record<string, unknown>): void {
  let script = document.getElementById(id) as HTMLScriptElement | null;

  if (!script) {
    script = document.createElement("script");
    script.id = id;
    script.type = "application/ld+json";
    document.head.appendChild(script);
  }

  script.textContent = JSON.stringify(data);
}

// Removes a structured-data block by id — used when a page that HAD
// structured data (e.g. a product page) unmounts, so a stale product's
// JSON-LD doesn't linger in <head> once the user navigates elsewhere.
export function removeJsonLd(id: string): void {
  document.getElementById(id)?.remove();
}

/**
 * noindex on authenticated pages — genuinely useful, not just decoration.
 * Here's a real SPA-specific problem:
 * if a crawler requests /cart while logged out,
 * ProtectedRoute redirects it to /login
 * using React Router's client-side <Navigate>
 * — which is not a real HTTP redirect a non-JS-executing bot would ever see;
 * it only happens after JavaScript runs.
 * A crawler that partially executes JS could
 * end up indexing /cart with confusing, half-rendered, or stale content.
 * Adding noindex directly to these pages is a deliberate
 * second layer of defense, independent of whatever the redirect does.
 */

/**
 * robots.txt and a static sitemap.xml — with an honest gap flagged.
 * These are plain static files, served as-is from Vite's public/ folder
 * — zero React involved.
 * But a real product sitemap (one URL per actual product in your database)
 * can't be generated by a pure frontend SPA at all;
 * it needs either a backend endpoint listing every product id,
 * or a build-time step that queries the database.
 * This is exactly the kind of gap worth flagging to Mohamed,
 * like the earlier cart/order include gaps
 * — the frontend alone cannot close it.
 */
